### PR TITLE
UUID via redfish

### PR DESCRIPTION
**Pull request by kolsa**

### CODE REVIEW

**Comment by kolsa** [comment]
Merge after https://github.com/metal-stack/go-hal/pull/9

**Review by majst01 — APPROVED** [review]

**Comment by majst01** [comment]
This is not reviewable anymore because its more or less the same than #7, we should first merge #7 if agreed and then see what are the changes for uuid via redfish

**Comment by kolsa** [comment]
:+1:

**Comment by majst01** [comment]
Closed after discussion and create a new one with the minimal changes required.

**Pull request closed without merging**
